#!/bin/bash

RELEASE=$1

OLDRELEASE=$(bc -l <<< "$RELEASE-1")

primary_arches=armv7hl,i686,x86_64
arm_arches=aarch64
ppc_arches=ppc64,ppc64le
s390_arches=s390x,s390


for arch in primary arm ppc s390
do

arches=$(echo $arch)_arches

if [ "$arch" == "primary" ]; then
kojicli=koji
else
kojicli=$arch-koji
fi

$kojicli add-tag --parent f$OLDRELEASE-updates f$RELEASE
$kojicli add-tag --parent f$RELEASE f$RELEASE-updates
$kojicli add-tag --parent f$RELEASE-updates f$RELEASE-updates-candidate
$kojicli add-tag --parent f$RELEASE-updates f$RELEASE-updates-testing
$kojicli add-tag --parent f$RELEASE-updates-testing f$RELEASE-updates-testing-pending
$kojicli add-tag --parent f$RELEASE-updates f$RELEASE-updates-pending
$kojicli add-tag --parent f$RELEASE-updates f$RELEASE-override
$kojicli add-tag --parent f$RELEASE-override --arches=$arches f$RELEASE-build
$kojicli add-tag-inheritance --priority 1 f$RELEASE-build f$OLDRELEASE-build
$kojicli edit-tag --perm=fedora-override f$RELEASE-override
$kojicli edit-tag --perm=admin f$RELEASE-updates
$kojicli edit-tag --perm=admin f$RELEASE-updates-testing
$kojicli edit-tag --perm=admin f$RELEASE-updates-testing-pending
$kojicli edit-tag --perm=admin f$RELEASE-updates-pending

$kojicli add-target f$RELEASE f$RELEASE-build
$kojicli add-target f$RELEASE-candidate f$RELEASE-build f$RELEASE
$kojicli edit-target rawhide --dest-tag=f$RELEASE --build-tag=f$RELEASE-build

done
