#!/bin/bash

# Copyright (C) 2013 Red Hat Inc.
# SPDX-License-Identifier:      GPL-2.0+


RELEASE=$1
BUILD=$2
VERSION=$3

GITHASH=$(git rev-parse --short HEAD)

    declare -l lspin
    lspin=$spin

if [ "$VERSION" == "rawhide" ]; then
TARGET=rawhide
else
TARGET=f$VERSION-candidate
fi

for spin in base
do
    declare -l lspin
    lspin=$spin
    url=http://kojipkgs.fedoraproject.org/mash/$VERSION-$BUILD/$VERSION/\$arch/os/
    kickstart=fedora-cloud-$lspin-$GITHASH.ks
    ksflatten -c fedora-cloud-$spin.ks -o $kickstart >& /dev/null
    echo "url --url=$url"|sed -e 's|$arch|$basearch|g' >> $kickstart
 koji image-build fedora-cloud-$spin $VERSION --distro Fedora-20 $TARGET --kickstart $kickstart $url x86_64 i386 --format=qcow2 --format=raw --release=$VERSION --scratch --repo=$url --nowait --disk-size=3
done
