#!/bin/bash

# Copyright (C) 2013 Red Hat Inc.
# SPDX-License-Identifier:	GPL-2.0+

# runs currently on relepel01.phx2.fedoraproject.org

DATE=$1
RSYNC_OPTS="-rlptDHhv --delay-updates"
DESTPATH="/pub/epel/beta/7/"
MOCKCONFIG=rhel-compose-x86_64


[ -z "$DATE" ] && {
	echo "usage: buildepelbeta <date>"
	exit 1
}

TMPDIR=`mktemp -d /tmp/epel.$DATE.XXXX`
mkdir -p /mnt/koji/mash/epel-$DATE/logs
echo "Compose started at `date --utc`" > /mnt/koji/mash/epel-$DATE/logs/start
echo >> /mnt/koji/mash/epel-$DATE/logs/start

# Emit a message using bodhi's cert (since we should be running as "masher").
echo "start" | fedmsg-logger \
    --cert-prefix bodhi \
    --modname compose \
    --topic epelbeta.start

pushd $TMPDIR
git clone git://git.fedorahosted.org/comps.git && {
	pushd comps
	make comps-epel7.xml
	cp comps-epel7.xml /mnt/koji/mash/epel-$DATE/logs/
	popd
}
popd

[ -f /mnt/koji/mash/epel-$DATE/logs/comps-epel7.xml ] || exit 1

mock -r $MOCKCONFIG --uniqueext=$DATE --init
mock -r $MOCKCONFIG --uniqueext=$DATE --no-clean --install koji yum createrepo cvs make intltool findutils mash yum-utils rsync repoview
# Copy in the hosts file so that we get the right address for koji
mock -r $MOCKCONFIG --uniqueext=$DATE --copyin /etc/hosts /etc/hosts >/dev/null 2>&1 # this reports to fail, but actually works
mock -r $MOCKCONFIG --uniqueext=$DATE --copyin /etc/mash/epel7.mash /etc/mash/epel7.mash > /dev/null 2>&1 # this reports to fail, but actually works
mock -r $MOCKCONFIG --uniqueext=$DATE --copyin /usr/share/mash/spam-o-matic-epel7 /usr/share/mash/spam-o-matic-epel7 > /dev/null 2>&1 # this reports to fail, but actually works
# Drop privs here so that we run as the masher UID
mock -r $MOCKCONFIG --uniqueext=$DATE --unpriv --chroot "mash -o /mnt/koji/mash/epel-$DATE --compsfile /mnt/koji/mash/epel-$DATE/logs/comps-epel7.xml epel7 > /mnt/koji/mash/epel-$DATE/logs/mash.log 2>&1" || exit 1

mock -r $MOCKCONFIG --uniqueext=$DATE --chroot "rm -f /var/lib/rpm/__db*"
mock -r $MOCKCONFIG --uniqueext=$DATE --unpriv --chroot "/usr/bin/repodiff -q --new=file:///mnt/koji/mash/epel-$DATE/epel7/SRPMS --old=file:///pub/epel/beta/7/SRPMS > /mnt/koji/mash/epel-$DATE/logs/repodiff"

mock -r $MOCKCONFIG --uniqueext=$DATE --unpriv --chroot "/usr/share/mash/spam-o-matic-epel7 --treename=epel-6 /mnt/koji/mash/epel-$DATE/epel7/ >/mnt/koji/mash/epel-$DATE/logs/depcheck" &


wait
mock -r $MOCKCONFIG --uniqueext=$DATE --clean

[ -n "$NOSYNC" ] && exit $rc

# Emit a message using bodhi's cert (since we should be running as "masher").
echo "done" | fedmsg-logger \
    --cert-prefix bodhi \
    --modname compose \
    --topic epelbeta.complete

cd /tmp
# data
sudo -u ftpsync /usr/bin/rsync $RSYNC_OPTS --exclude repodata/ /mnt/koji/mash/epel-$DATE/epel7/ $DESTPATH
# repodata & cleanup
sudo -u ftpsync /usr/bin/rsync $RSYNC_OPTS --delete --delete-after /mnt/koji/mash/epel-$DATE/epel7/ $DESTPATH
if [ "$?" = "0" ]; then
    cat /mnt/koji/mash/epel-$DATE/logs/start /mnt/koji/mash/epel-$DATE/logs/depcheck /mnt/koji/mash/epel-$DATE/logs/repodiff | mutt -e 'set from="EPEL Beta Report <epel@fedoraproject.org>"' -e 'set envelope_from=yes' -s 'epel beta report: '$DATE' changes' epel-devel@lists.fedoraproject.org
fi
exit 0
