#!/bin/bash

ARCHES="i686 x86_64"

DATE=`date +%Y%m%d.%H`

RELEASE=16-Beta
VERSION=16

TARGET=f16

GITHASH=$(git rev-parse --short HEAD)

#SPINS="LXDE XFCE"
SPINS="Desktop KDE LXDE XFCE"
#SPINS="Design-suite Desktop KDE LXDE Meego Security SoaS XFCE"

for spin in $SPINS
do
    declare -l lspin
    lspin=$spin
    ksflatten fedora-livecd-$lspin.ks -o fedora-livecd-$lspin-$GITHASH.ks >& /dev/null
    for ARCH in $ARCHES
    do
       if [[ $ARCH == i686 ]]
         then BASEARCH=i386
         else BASEARCH=$ARCH
       fi
    koji spin-livecd   --noprogress --isoname Fedora-$RELEASE-$ARCH-Live-$spin.iso --nowait  --repo=http://infrastructure.fedoraproject.org/pub/fedora/linux/development/$VERSION/$BASEARCH/os/,http://kojipkgs.fedoraproject.org/mash/bleed/$BASEARCH/ $TARGET $ARCH fedora-livecd-$lspin-$GITHASH.ks
   done
done

#PINS="Games"

#or spin in $SPINS
#o
#   declare -l lspin
#   lspin=$spin
#   ksflatten fedora-livedvd-$lspin.ks -o fedora-livedvd-$lspin-$GITHASH.ks >& /dev/null
#   for ARCH in $ARCHES
#   do
#      if [[ $ARCH == i686 ]]
#        then BASEARCH=i386
#        else BASEARCH=$ARCH
#      fi
#   koji spin-livecd   --noprogress --isoname Fedora-$RELEASE-$ARCH-Live-$spin.iso --nowait  --repo=http://infrastructure.fedoraproject.org/pub/fedora/linux/development/$VERSION/$BASEARCH/os/,http://kojipkgs.fedoraproject.org/mash/bleed/$BASEARCH/ $TARGET $ARCH fedora-livedvd-$lspin-$GITHASH.ks
#  done
#one
