#!/bin/bash

# Copyright (C) 2012 Red Hat Inc.
# SPDX-License-Identifier:  GPL-2.0+

# runs currently on releng03.phx2.fedoraproject.org
set -x

DATE=$1
ARCH=$2
ENVIRONMENT=${3:-production}

BRANCHED="21"
DIST=branched
COMPSFILE="comps-f${BRANCHED}.xml"
GIT_BRANCH="f${BRANCHED}"

TREEPREFIX="/pub/fedora/linux"
RSYNC_EXTRA_OPTS="--link-dest=$TREEPREFIX/development/rawhide/"
MASHDIR="/mnt/koji/mash/${DIST}-$DATE"
EXPANDARCH=""
DEPOPTS="--treename F-$BRANCHED"
MASHOPTS=""
MOCK="/usr/bin/mock"
MOCKCONFIG="fedora-${DIST}-compose-i386"
TOMAIL="devel@lists.fedoraproject.org test@lists.fedoraproject.org"
SUBJECT='F-'$BRANCHED' Branched report: '$DATE' changes'
FROM="Fedora Branched Report <rawhide@fedoraproject.org>"
RSYNCPREFIX="sudo -u ftpsync"
ATOMIC=$(mktemp -d /tmp/atomici.${DIST}.$DATE.XXXX)
ATOMICREPO="/mnt/fedora_koji/koji/mash/atomic/$BRANCHED/"
ATOMICDEST="/pub/fedora/linux/atomic/$BRANCHED/"

source ./scripts/build-functions.sh
