#!/bin/bash

# Copyright (C) 2013 Red Hat Inc.
# SPDX-License-Identifier:      GPL-2.0+


RELEASE=$1
BUILD=$2
VERSION=$3

GITHASH=$(git rev-parse --short HEAD)

    declare -l lspin
    lspin=$spin

if [ "$VERSION" == "rawhide" ]; then
TARGET=rawhide
else
TARGET=f$VERSION-candidate
fi

for spin in base
do
    declare -l lspin
    lspin=$spin
    ksflatten -c fedora-cloud-$spin.ks -o fedora-cloud-$spin-$GITHASH.ks >& /dev/null
 koji  image-build fedora-cloud-$spin $VERSION --distro Fedora-19 $TARGET --kickstart fedora-cloud-$spin-$GITHASH.ks http://kojipkgs.fedoraproject.org/mash/$VERSION-$BUILD/$VERSION/\$arch/os/ x86_64 i386 --disk-size=3G --format=qcow2 --format=raw --release=$VERSION --scratch --repo=http://kojipkgs.fedoraproject.org/mash/$VERSION-$BUILD/$VERSION/\$arch/os/ --nowait
done
