#!/bin/bash

# Copyright (C) 2012 Red Hat Inc.
# SPDX-License-Identifier:	GPL-2.0+

# runs currently on releng03.phx2.fedoraproject.org

DATE=$1
ARCH=$2

BRANCHED="21"
DIST=branched

TREEPREFIX="/pub/fedora/linux"
MASHDIR="/mnt/koji/mash/branched-$DATE"
EXPANDARCH=""
DEPOPTS="--treename F-$BRANCHED"
MASHOPTS=""
MOCKCONFIG=fedora-branched-compose-i386
MAIL="devel@lists.fedoraproject.org,test@lists.fedoraproject.org"
SUBJECT='F-'$BRANCHED' Branched report: '$DATE' changes'
FROM="Fedora Branched Report <rawhide@fedoraproject.org>"
RSYNCPREFIX="sudo -u ftpsync"
[ -n "$ARCH" ] && {
TREEPREFIX="/mnt/koji/tree"
EXPANDARCH="-$ARCH"
DEPOPTS="--treename F-$BRANCHED --nomail"
MASHOPTS="-c /etc/mash/mash.$ARCH.conf"
MAIL="secondary@lists.fedoraproject.org,$ARCH@lists.fedoraproject.org"
SUBJECT=$ARCH' F-'$BRANCHED' Branched report: '$DATE' changes'
FROM=$ARCH' Fedora Branched Report <rawhide@fedoraproject.org>'
RSYNCPREFIX=""
}

[ "$ARCH" == "ppc" ] && {
MOCKCONFIG=fedora-branched-compose-ppc64

}
 
RSYNC_OPTS="-rlptDHhv --delay-updates"
DESTPATH="$TREEPREFIX/development/$BRANCHED/"

# basepath of $0
scriptname="${0##*/}
[ -z "$DATE" ] && {
	echo "usage: ${scriptname} <date>"
	exit 1
}

TMPDIR=`mktemp -d /tmp/${DIST}.$DATE.XXXX`
logdir="/mnt/koji/mash/${DIST}-$DATE/logs"
mkdir -p "${logdir}"


echo "Compose started at $(date --utc)" > "$logdir/start"



logfile="${logdir}/build${DIST}.log"
touch "${logfile}"
function log()
{
	message="${1}"
	echo "$(date --utc) build${DIST}: ${message}" >> "${logfile}"
}

function send_fedmsg()
{
	topic="${1}"
	log="${2}"
	# Emit a message using bodhi's cert (since we should be running as "masher").
	echo "{\"log\": \"${log}\", \"branch\": \"$BRANCHED\", \"arch\": \"$ARCH\"}" | fedmsg-logger \
		--cert-prefix bodhi \
		--modname compose \
		--topic "${DIST}.${topic}" \
		--json-input
}

log "started"
send_fedmsg start start

log "blocking retired packages"
./scripts/block_retired.py

log "git clone of comps started"
pushd $TMPDIR
git clone git://git.fedorahosted.org/comps.git && {
	pushd comps
	make comps-f$BRANCHED.xml
	cp comps-f$BRANCHED.xml $logdir/
	popd
}
popd
log "git clone of comps finished"

[ -f $logdir/comps-f$BRANCHED.xml ] || exit 1

log "mock init"
mock -r $MOCKCONFIG --uniqueext=$DATE --init
log "mock install base packages"
mock -r $MOCKCONFIG --uniqueext=$DATE --no-clean --install koji yum createrepo cvs make intltool findutils mash yum-utils rsync repoview hardlink
# until we move to bodhi lets not be strict about the gpg keys
mock -r $MOCKCONFIG --uniqueext=$DATE --chroot "sed -i -e 's|strict_keys = True|strict_keys = False|g' /etc/mash/branched.mash"
#disable delta close to release as we do not want them in the final trees
mock -r $MOCKCONFIG --uniqueext=$DATE --chroot "sed -i -e 's|delta = True|delta = False|g' /etc/mash/branched.mash"
# secondary arches are a bit harder to make sure everything is signed lets not be too strict, but actual release compsoes need to be.
[ -n "$ARCH" ] && {
mock -r $MOCKCONFIG --uniqueext=$DATE --chroot "sed -i -e 's|strict_keys = True|strict_keys = False|g' /etc/mash/branched.$ARCH.mash"
}

# Copy in the hosts file so that we get the right address for koji
log "mock setup /etc/hosts"
mock -r $MOCKCONFIG --uniqueext=$DATE --copyin /etc/hosts /etc/hosts >/dev/null 2>&1 # this reports to fail, but actually works

send_fedmsg start mash.start

log "starting mash"
# Drop privs here so that we run as the masher UID
mock -r $MOCKCONFIG --uniqueext=$DATE --unpriv --chroot "mash $MASHOPTS -p $TREEPREFIX/development/$BRANCHED -o /mnt/koji/mash/branched-$DATE --compsfile $logdir/comps-f$BRANCHED.xml $BRANCHED$EXPANDARCH > $logdir/mash.log 2>&1" || exit 1

send_fedmsg done mash.complete

log "finished mash"
log "starting hardlink"
# hardlink the noarch deltarpms between x86_64 and i386 
mock -r $MOCKCONFIG --uniqueext=$DATE --chroot "hardlink -v -c /mnt/koji/mash/branched-$DATE/$BRANCHED$EXPANDARCH"
log "finished hardlink"

log "starting repodiff"
mock -r $MOCKCONFIG --uniqueext=$DATE --chroot "rm -f /var/lib/rpm/__db*"
mock -r $MOCKCONFIG --uniqueext=$DATE --unpriv --chroot "/usr/bin/repodiff -s -q --new=file:///mnt/koji/mash/branched-$DATE/$BRANCHED$EXPANDARCH/source/SRPMS --old=file://$TREEPREFIX/development/$BRANCHED/source/SRPMS > $logdir/repodiff"
log "finished repodiff"
mock -r $MOCKCONFIG --uniqueext=$DATE --unpriv --chroot "/usr/share/mash/spam-o-matic $DEPOPTS /mnt/koji/mash/branched-$DATE/$BRANCHED$EXPANDARCH >$logdir/depcheck" &


send_fedmsg start pungify.start

log "starting critppath generation"
#only run critpath on primary arch
[ -z "$ARCH" ] && {
./scripts/critpath.py --url file:///mnt/koji/mash/$DIST-$DATE/$BRANCHED/ -o /mnt/koji/mash/$DIST-$DATE/logs/critpath.txt branched &> /mnt/koji/mash/$DIST-$DATE/logs/critpath.log
log "finished critppath generation"

log "starting pungify"
for basearch in armhfp i386 x86_64 ; do
    HOST=$(koji list-hosts --quiet --enabled --ready --arch=$basearch  --channel compose | sed 's|/| |g' | sort -g -k4 -k5r | awk -F ' ' '{ print $1 ; exit }')
    ./scripts/pungify $DATE $BRANCHED $basearch $HOST $DIST > $logdir/pungify-$basearch.log 2>&1 &
    done
}
wait
log "finished pungify"

send_fedmsg done pungify.complete

log "starting build_composeinfo"
echo "Running build_composeinfo"
./scripts/build_composeinfo --name Fedora-${BRANCHED}-${DATE} /mnt/koji/mash/$DIST-$DATE/$BRANCHED/

log "finished build_composeinfo"
log "starting mock clean"
mock -r $MOCKCONFIG --uniqueext=$DATE --clean
log "finished mock clean"

[ -n "$NOSYNC" ] && exit $rc

log "started linking finished tree"
# Create a rawhide link in /mnt/koji/mash, deltas et al depend on this
rm /mnt/koji/mash/$DIST
ln -s /mnt/koji/mash/$DIST-$DATE/$BRANCHED$EXPANDARCH/ /mnt/koji/mash/$DIST
log "finished linking finished tree"

echo "Compose finished at $(date --utc)" >> $logdir/finish
echo >> $logdir/finish
log "finished compose"

send_fedmsg start rsync.start

# data
$RSYNCPREFIX /usr/bin/rsync $RSYNC_OPTS --link-dest=$TREEPREFIX/development/rawhide/ --exclude repodata/ /mnt/koji/mash/branched-$DATE/$BRANCHED$EXPANDARCH/ $DESTPATH
# repodata & cleanup
$RSYNCPREFIX /usr/bin/rsync $RSYNC_OPTS --link-dest=$TREEPREFIX/development/rawhide/ --delete --delete-after /mnt/koji/mash/branched-$DATE/$BRANCHED$EXPANDARCH/ $DESTPATH

if [ "$?" = "0" ]; then
   export mail=0
fi

send_fedmsg done rsync.complete

log "starting sending email report"
if [ "$mail" = "0" ]; then
    cat $logdir/start $logdir/depcheck $logdir/repodiff $logdir/finish |  mutt -e "set from=\"$FROM\"" -e 'set envelope_from=yes' -s "$SUBJECT" $MAIL
fi
log "finished sending email report"

[ -z "$ARCH" ] && {
send_fedmsg start image.start

log "started checking out spin-kickstarts"
pushd ../
git clone git://git.fedorahosted.org/git/spin-kickstarts/
pushd spin-kickstarts
git checkout f$BRANCHED
log "finished checking out spin-kickstarts"
log "started building live/arm/cloud images"
../releng/scripts/build-livecds $BRANCHED $DATE $BRANCHED
../releng/scripts/build-arm-images $BRANCHED $DATE $BRANCHED
../releng/scripts/build-cloud-images $BRANCHED $DATE $BRANCHED
log "finished starting building live/arm/cloud images"
popd
popd

send_fedmsg done image.complete
}

for koji in arm ppc s390
do
  if [ "$koji" = "arm" ]; then
     arches=aarch64
  elif [ "$koji" = "ppc" ]; then
     arches=ppc64,ppc64le
  elif [ "$koji" = "s390" ]; then
     arches=s390,s390x
  fi
  scripts/srpm-excluded-arch.py -a $arches --path /mnt/koji/mash/branched-$DATE/$BRANCHED$EXPANDARCH/source/SRPMS/\*/ >$logdir/excludearch-$koji.log
done

send_fedmsg done complete

exit 0
