#!/bin/bash

# Copyright (C) 2013 Red Hat Inc.
# SPDX-License-Identifier:      GPL-2.0+


RELEASE=$1
BUILD=$2
VERSION=$3
COMPOSE=$4

GITHASH=$(git rev-parse --short HEAD)

    declare -l lspin
    lspin=$spin

if [ "$VERSION" == "rawhide" ]; then
TARGET=rawhide
BRANCH=rawhide
else
TARGET=f$VERSION-candidate
BRANCH=branched
fi

for spin in Base
do
    declare -l lspin
    lspin=$spin
    url=http://compose-x86-02.phx2.fedoraproject.org/compose/$VERSION$COMPOSE/$VERSION/Cloud/\$arch/os/
    kickstart=fedora-cloud-$lspin-$GITHASH.ks
    ksflatten -c fedora-cloud-$lspin.ks -o $kickstart >& /dev/null
    echo "url --url=$url"|sed -e 's|$arch|$basearch|g' >> $kickstart
 #koji image-build fedora-cloud-$spin $VERSION --distro Fedora-20 $TARGET --ksurl=git://git.fedorahosted.org/git/spin-kickstarts.git?#$GITHASH --kickstart=fedora-cloud-$lspin.ks $url x86_64 i386 --format=qcow2 --format=raw --release=$VERSION --scratch --repo=$url --nowait --disk-size=3
    koji image-build Fedora-Cloud-$spin $BUILD --distro Fedora-20 $TARGET  --kickstart=fedora-cloud-$lspin-$GITHASH.ks $url x86_64 i386 --format=qcow2 --format=raw-xz --release=$RELEASE --scratch --repo=$url --nowait --disk-size=3
done

for spin in Atomic
do
    declare -l lspin
    lspin=$spin
    url=http://compose-x86-02.phx2.fedoraproject.org/compose/$VERSION$COMPOSE/$VERSION/Cloud/\$arch/os/
    kickstart=fedora-cloud-$lspin-$GITHASH.ks
    ksflatten -c fedora-cloud-$lspin.ks -o $kickstart >& /dev/null
    echo "url --url=$url"|sed -e 's|$arch|$basearch|g' >> $kickstart
 #koji image-build fedora-cloud-$spin $VERSION --distro Fedora-20 $TARGET --ksurl=git://git.fedorahosted.org/git/spin-kickstarts.git?#$GITHASH --kickstart=fedora-cloud-$lspin.ks $url x86_64 i386 --format=qcow2 --format=raw --release=$VERSION --scratch --repo=$url --nowait --disk-size=3
    koji image-build Fedora-Cloud-$spin $BUILD --distro Fedora-20 $TARGET  --kickstart=fedora-cloud-$lspin-$GITHASH.ks $url x86_64 --format=qcow2 --format=raw-xz --release=$RELEASE --scratch --repo=$url --nowait --disk-size=3
done

for spin in Base
do
    declare -l lspin
    lspin=$spin
    url=http://compose-x86-02.phx2.fedoraproject.org/compose/$VERSION$COMPOSE/$VERSION/Cloud/\$arch/os/
    kickstart=fedora-docker-$lspin-$GITHASH.ks
    ksflatten -c fedora-docker-$lspin.ks -o $kickstart >& /dev/null
    echo "url --url=$url"|sed -e 's|$arch|$basearch|g' >> $kickstart
 #koji image-build fedora-cloud-$spin $VERSION --distro Fedora-20 $TARGET --ksurl=git://git.fedorahosted.org/git/spin-kickstarts.git?#$GITHASH --kickstart=fedora-cloud-$lspin.ks $url x86_64 i386 --format=qcow2 --format=raw --release=$VERSION --scratch --repo=$url --nowait --disk-size=3
    koji image-build Fedora-Docker-$spin $BUILD --distro Fedora-20 $TARGET  --kickstart=fedora-docker-$lspin-$GITHASH.ks $url x86_64  --format=docker --release=$RELEASE --scratch --repo=$url --nowait --disk-size=3
done
