#!/bin/bash

# Copyright (C) 2013 Red Hat Inc.
# SPDX-License-Identifier:	GPL-2.0+

ARCHES="i686 x86_64"

RELEASE=$1
BUILD=$2
VERSION=$3

if [ "$VERSION" == "rawhide" ]; then
TARGET=rawhide
else
TARGET=f$VERSION-candidate
fi

GITHASH=$(git rev-parse --short HEAD)

SPINS="KDE LXDE MATE-Compiz Security SoaS Xfce"
for spin in $SPINS
do
    declare -l lspin
    lspin=$spin
    ksflatten fedora-livecd-$lspin.ks -o fedora-livecd-$lspin-$GITHASH.ks >& /dev/null
    for ARCH in $ARCHES
    do
       if [[ $ARCH == i686 ]]
         then BASEARCH=i386
         else BASEARCH=$ARCH
       fi
    koji spin-livecd --scratch  --release $BUILD --noprogress Fedora-Live-$spin-$ARCH $RELEASE --nowait  --repo=http://infrastructure.fedoraproject.org/pub/fedora/linux/development/$VERSION/$BASEARCH/os/ --repo=http://kojipkgs.fedoraproject.org/mash/bleed/$BASEARCH/ $TARGET $ARCH fedora-livecd-$lspin-$GITHASH.ks
   done
done

SPINS="Games Electronic-Lab Robotics Scientific-KDE"
for spin in $SPINS
do
    declare -l lspin
    lspin=$spin
    ksflatten fedora-livedvd-$lspin.ks -o fedora-livedvd-$lspin-$GITHASH.ks >& /dev/null
    for ARCH in $ARCHES
    do
       if [[ $ARCH == i686 ]]
         then BASEARCH=i386
         else BASEARCH=$ARCH
       fi
    koji spin-livecd --scratch --release $BUILD --noprogress Fedora-Live-$spin-$ARCH $RELEASE --nowait  --repo=http://infrastructure.fedoraproject.org/pub/fedora/linux/development/$VERSION/$BASEARCH/os/ --repo=http://kojipkgs.fedoraproject.org/mash/bleed/$BASEARCH/ $TARGET $ARCH fedora-livedvd-$lspin-$GITHASH.ks
   done
done

SPINS="Workstation Design-suite Jam-KDE"
for spin in $SPINS
do
    declare -l lspin
    lspin=$spin
    ksflatten fedora-live-$lspin.ks -o fedora-live-$lspin-$GITHASH.ks >& /dev/null
    for ARCH in $ARCHES
    do
       if [[ $ARCH == i686 ]]
         then BASEARCH=i386
         else BASEARCH=$ARCH
       fi
    koji spin-livecd --scratch --release $BUILD --noprogress Fedora-Live-$spin-$ARCH $RELEASE --nowait  --repo=http://infrastructure.fedoraproject.org/pub/fedora/linux/development/$VERSION/$BASEARCH/os/ --repo=http://kojipkgs.fedoraproject.org/mash/bleed/$BASEARCH/ $TARGET $ARCH fedora-live-$lspin-$GITHASH.ks
   done
done
