#!/bin/bash

# Copyright (C) 2012 Red Hat Inc.
# SPDX-License-Identifier:	GPL-2.0+

ARCHES="armv7hl"

RELEASE=$1
BUILD=$2
VERSION=$3

if [ "$VERSION" == "rawhide" ]; then
TARGET=rawhide
else
TARGET=f$VERSION-candidate
fi

GITHASH=$(git rev-parse --short HEAD)

SPINS="Minimal Workstation KDE LXDE Mate SoaS Xfce"
for spin in $SPINS
do
    declare -l lspin
    lspin=$spin
    ksflatten fedora-arm-$lspin.ks -o fedora-arm-$lspin-$GITHASH.ks >& /dev/null
    for ARCH in $ARCHES
    do
       if [[ $ARCH == armv7hl ]]
         then BASEARCH=armhfp
         else BASEARCH=$ARCH
       fi
    koji spin-appliance --scratch --release $BUILD --nowait Fedora-$spin-$BASEARCH $RELEASE  --repo=http://infrastructure.fedoraproject.org/pub/fedora/linux/development/$VERSION/$BASEARCH/os/ --repo=http://kojipkgs.fedoraproject.org/mash/bleed/$BASEARCH/ $TARGET $ARCH fedora-arm-$lspin-$GITHASH.ks
   done
done


