#!/usr/bin/python -tt
# vim: fileencoding=utf8
# SPDX-License-Identifier: GPL-2.0+

import argparse
import datetime
import os
import shutil
import subprocess
import tempfile

ORPHAN_REASON = """Retired orphaned package, because it was orphaned for
more than six weeks.
"""


def retire(pkg, branch, reason, dryrun=False):
    def run(cmd, cwd):
        if dryrun:
            print(cmd)
        else:
            return subprocess.check_call(cmd, cwd=cwd)

    tempdir = tempfile.mkdtemp(pkg, branch)
    try:
        cmd = ["fedpkg", "clone", pkg]
        run(cmd, tempdir)

        pkgdir = os.path.join(tempdir, pkg)

        cmd = ["fedpkg", "switch-branch", branch]
        run(cmd, pkgdir)

        cmd = ["fedpkg", "retire", reason]
        run(cmd, pkgdir)
    finally:
        shutil.rmtree(tempdir)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Helper to retire packages")
    parser.add_argument("--branch", default="master", nargs="*",
                        choices=["master", "f23", "f22", "f21", "f20",
                                 "epel7", "el6", "el5"])
    parser.add_argument("--reasonfile", default=None)
    parser.add_argument("--reason", default=None)
    parser.add_argument("--orphan", default=False, action="store_true",
                        help="Use reason for orphaned packages")
    parser.add_argument("pkg", nargs="+")
    args = parser.parse_args()

    if args.reasonfile is None and args.reason is None and not args.orphan:
        reasonfile = tempfile.NamedTemporaryFile(delete=False)
        filename = reasonfile.name
        childpid = os.fork()
        if childpid == 0:
            os.execlp("vim", "vim", filename)
        else:
            os.waitpid(childpid, 0)
        reason = reasonfile.read()
        os.unlink(filename)
    elif args.reasonfile is not None:
        with open(args.reasonfile, "rb") as reasonfile:
            reason = reasonfile.read()
    elif args.reason:
        reason = args.reason
    elif args.orphan:
        reason = ORPHAN_REASON

    date = datetime.datetime.now().strftime("%Y-%m-%d: ")
    if not reason.startswith(date):
        reason = date + reason

    if reason[-1] != "\n":
        reason += "\n"

    errors = {}
    for pkg in args.pkg:
        retired = False
        for branch in args.branch:
            for _ in xrange(0, 3):
                try:
                    retire(pkg, branch, reason, dryrun=False)
                    retired = True
                    break
                except subprocess.CalledProcessError:
                    pass
            if not retired:
                errors.setdefault(branch, []).append(pkg)

    if errors:
        print("Errors: " + repr(errors))
