#!/bin/bash


# Copyright (C) 2015 Red Hat, Inc.
# SPDX-License-Identifier:      GPL-2.0+

VERSION=$1
COMPOSE=$2
DATE=$3
BRANCH=$(echo $VERSION|sed -e 's|_.*||g')
DESTDIR=/srv/pungi/$VERSION-$DATE/
FINALDEST=/mnt/fedora_koji/compose/$VERSION-$DATE/
KICKSTARTS=/srv/pungi/spin-kickstarts/
ATOMIC=/srv/pungi/fedora-atomic/
ATOMICDEST=/srv/pungi/atomic/

SHORTCOMPOSE=$(echo $COMPOSE|sed -e 's|_RC||g')
SHORTVERSION=$VERSION
[ -z "$COMPOSE" ] && {
        SHORTVERSION=$(echo $VERSION|sed -e 's|_T.*||')
        SHORTCOMPOSE=$(echo $VERSION|sed -e 's|.*_||g')
}

FULLPATH=$(pwd)
pushd $KICKSTARTS
git reset --hard
git checkout f$VERSION 
git pull --rebase

$FULLPATH/build-cloud-images "$VERSION" "$DATE" "$BRANCH" "$COMPOSE"
popd


while true
do
  if [ $(koji list-tasks --mine|grep OPEN|grep -e image -e livecd -e appliance|wc -l) -ne 0 ]
  then
    echo "image, appliance or livecd tasks running, waiting 2 minutes"
    sleep 120
  else
    break
  fi
done

sg releng "mkdir -p $FINALDEST"
pushd $FINALDEST/
sg releng "mkdir -p Cloud-Images/i386/Images Cloud-Images/x86_64/Images Docker/x86_64"
popd


USER=$(whoami)
# stage images
sg releng "sudo /usr/bin/cp -l /mnt/fedora_koji/koji/scratch/$USER/task_*/Fedora-Cloud*$VERSION-$DATE\.i386.raw.xz $FINALDEST/Cloud-Images/i386/Images/"
sg releng "sudo /usr/bin/cp -l /mnt/fedora_koji/koji/scratch/$USER/task_*/Fedora-Cloud*$VERSION-$DATE\.i386.qcow2 $FINALDEST/Cloud-Images/i386/Images/"
sg releng "sudo /usr/bin/cp -l /mnt/fedora_koji/koji/scratch/$USER/task_*/Fedora-Cloud*$VERSION-$DATE\.x86_64.raw.xz $FINALDEST/Cloud-Images/x86_64/Images/"
sg releng "sudo /usr/bin/cp -l /mnt/fedora_koji/koji/scratch/$USER/task_*/Fedora-Cloud*$VERSION-$DATE\.x86_64.qcow2 $FINALDEST/Cloud-Images/x86_64/Images/"
sg releng "sudo /usr/bin/cp -l /mnt/fedora_koji/koji/scratch/$USER/task_*/Fedora-Cloud*$VERSION-$DATE\.x86_64.*.ova $FINALDEST/Cloud-Images/x86_64/Images/"
sg releng "sudo /usr/bin/cp -l /mnt/fedora_koji/koji/scratch/$USER/task_*/Fedora-Docker*-$VERSION-$DATE*tar.gz $FINALDEST//Docker/x86_64/"



pushd $FINALDEST/Cloud-Images
for arch in i386 x86_64; do pushd $arch/Images; sg releng "sha256sum --tag -b *qcow2 *raw.xz *ova>  Fedora-Cloud-Images-$arch-$VERSION-CHECKSUM"; popd; done
popd

pushd $FINALDEST/Docker/x86_64
sg releng "sha256sum --tag -b *tar.gz>  Fedora-Docker-x86_64-$VERSION-CHECKSUM"
popd


# stage the composed tree to final locateion
sg releng "mkdir /pub/alt/stage/$VERSION-$DATE/"
sg releng "chmod 700 /pub/alt/stage/$VERSION-$DATE/"
for type in Docker Cloud-Images; do sg releng "rsync -avhH $FINALDEST/$type/ /pub/alt/stage/$VERSION-$DATE/$type/"; done
sg releng "chmod 755 /pub/alt/stage/$VERSION-$DATE/"

