#!/bin/sh -x

# pungify - run pungi on a particular rawhide tree
# needs passed:
#	the tree version (usually a datestamp)
#	the arch
#	the hostname to connect to (can be user@host)
#
# Hosts must have valid mock development configs. More paths are hardcoded in this script than probably should be.

TREE=$1

BRANCH=$2

ARCH=$3

HOST=$4

usage() {
	echo "Usage: pungify <tree> <branch> <arch> <host>"
	exit 1
}	

[ -z "$TREE" -o -z "$BRANCH" -o -z "$ARCH" -o -z "$HOST" ] && usage

ssh mock@$HOST /bin/bash -- << EOF
	set -x
	mock -r fedora-devel-pungi-$ARCH --uniqueext=$TREE --init || exit 1
	mock -r fedora-devel-pungi-$ARCH --uniqueext=$TREE --install pungi nfs-utils setarch || exit 1
	mock -r fedora-devel-pungi-$ARCH --uniqueext=$TREE --arch $ARCH shell -- << EEE
set -x
mkdir -p /tmp/treebuild.$TREE/{output,cache,$BRANCH}
cd /tmp/treebuild.$TREE
touch rawhide.ks
mount -t nfs -o ro,nolock nfs01.phx2.fedoraproject.org:/mnt/koji/mash/branched-$TREE/$BRANCH $BRANCH
rm -f /var/lib/rpm/__db*
mkdir -p output/$BRANCH/$ARCH/os/
ln -s /tmp/treebuild.$TREE/$BRANCH/$ARCH/os/Packages output/$BRANCH/$ARCH/os/Packages
ln -s /tmp/treebuild.$TREE/$BRANCH/$ARCH/os/repodata output/$BRANCH/$ARCH/os/repodata
pungi -c ./rawhide.ks -B --destdir /tmp/treebuild.$TREE/output --cachedir /tmp/treebuild.$TREE/cache --ver $BRANCH
umount $BRANCH
rm -rf output/$BRANCH/$ARCH/os/{Packages,repodata}
EEE
EOF
# so, so wrong
rsync -vaH mock@$HOST:/var/lib/mock/fedora-development-pungi-$ARCH-$TREE/root/tmp/treebuild.$TREE/output/$BRANCH/$ARCH/os/ /mnt/koji/mash/branched-$TREE/$BRANCH/$ARCH/os/
rsync -vaH mock@$HOST:/var/lib/mock/fedora-development-pungi-$ARCH-$TREE/root/tmp/treebuild.$TREE/output/logs/* /mnt/koji/mash/branched-$TREE/logs/
ssh mock@$HOST /bin/bash -- << EOF
	set -x
	mock -r fedora-devel-pungi-$ARCH --uniqueext=$TREE clean
EOF
