#!/bin/bash

pushd ~/src/releng/scripts

while [ 1 ]
do
	(./sigulsign_unsigned.py -vv fedora-12 --tag=dist-f12-updates-candidate --password="$1") &
	(./sigulsign_unsigned.py -vv fedora-11 --tag=dist-f11-updates-candidate --password="$1") &

	wait
	sleep 1800
done
