#!/bin/sh

# Copyright (C) 2013 Red Hat, Inc.
# SPDX-License-Identifier:      GPL-2.0+

tags_updates="f22 f21-updates f20-updates"
tags_testing="f21-updates-testing f20-updates-testing"
tags_candidate="f21-updates-candidate f20-updates-candidate"

for arch in arm ppc s390
do
    ./sync-tagged-primary.py $arch $tags_updates
    ./sync-tagged-primary.py $arch $tags_testing
    ./sync-tagged-primary.py $arch $tags_candidate
    ./sync-tagged-primary.py $arch trashcan
done
