#!/bin/sh

tags_updates="f20 f19-updates f18-updates"
tags_testing="f18-updates-testing f19-updates-testing"

for arch in arm ppc s390
do
    ./sync-tagged-primary.py $arch $tags_updates
    ./sync-tagged-primary.py $arch $tags_testing
done
